### ISSUE TITLE
[12.0] sale_isolated_quotation has error during uninstall

### ISSUE THREAD

**Issue by jchanme** [OCA/sale-workflow#1084]
This module is installed on new Odoo 12 installation with CRM, Sales installed and then there is this error when I tried to uninstall it, below is the debug log. Anyone has ideas?

> Traceback (most recent call last):
  File "/opt/odoo/odoo-12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-12/odoo/modules/loading.py", line 484, in load_modules
    getattr(py_module, uninstall_hook)(cr, registry)
  File "/opt/odoo/addons-test/sale_isolated_quotation/hooks.py", line 23, in uninstall_hook
    del ctx['order_sequence']
KeyError: 'order_sequence'
2020-03-05 04:50:03,546 23329 ERROR safyric odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-12/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-12/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-12/odoo/addons/base/wizard/base_module_uninstall.py", line 60, in action_uninstall
    return modules.button_immediate_uninstall()
  File "<decorator-gen-64>", line 2, in button_immediate_uninstall
  File "/opt/odoo/odoo-12/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo-12/odoo/addons/base/models/ir_module.py", line 586, in button_immediate_uninstall
    return self._button_immediate_function(type(self).button_uninstall)
  File "/opt/odoo/odoo-12/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo-12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-12/odoo/modules/loading.py", line 484, in load_modules
    getattr(py_module, uninstall_hook)(cr, registry)
  File "/opt/odoo/addons-test/sale_isolated_quotation/hooks.py", line 23, in uninstall_hook
    del ctx['order_sequence']
KeyError: 'order_sequence'

**Comment by yrismawan** [comment]
I Have same issue ...

**Comment by yrismawan** [comment]
I don't know why after upgrading the core, I can uninstall the module and install again
