### ISSUE TITLE
sale_validity gives error: Can't render view sale_validity.view_order_form_validity for model: sale.order

### ISSUE THREAD

**Issue by LeartS** [OCA/sale-workflow#13]
The module `sale_validity` fails on startup, as you can see from [this Travis report](https://travis-ci.org/OCA/sale-workflow/jobs/32009263).
The status of the branch is green because of issue https://github.com/OCA/maintainer-quality-tools/issues/60, but it makes every pull request fail.

The relevant line of error seems to be:

```
AttributeError: View definition error for inherited view 'sale_stock.view_order_form_inherit' on model 'sale.order': Element '<xpath expr="//button[@name='action_cancel']">' not found in parent view 'sale.view_order_form'
```

Which I really don't understand given sale_validity's [sale_order.xml code](https://github.com/OCA/sale-workflow/blob/7.0/sale_validity/view/sale_order.xml)

```
2014-08-08 12:56:55,416 23157 ERROR openerp_test openerp.addons.base.ir.ir_ui_view: Can't render view sale_validity.view_order_form_validity for model: sale.order
Traceback (most recent call last):
  File "/home/travis/build/OCA/odoo-7.0/openerp/addons/base/ir/ir_ui_view.py", line 126, in _check_render_view
    fvg = self.pool.get(view.model).fields_view_get(cr, uid, view_id=view.id, view_type=view.type, context=context)
  File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 2263, in fields_view_get
    arch=apply_view_inheritance(cr, user, source, sql_res['id']),
  File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 2221, in apply_view_inheritance
    source = apply_inheritance_specs(source, view_arch, view_id)
  File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 2205, in apply_inheritance_specs
    raise_view_error("Element '%s' not found in parent view '%%(parent_xml_id)s'" % tag, inherit_id)
  File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 2098, in raise_view_error
    %  (child_view.xml_id, self._name, error_msg))
AttributeError: View definition error for inherited view 'sale_stock.view_order_form_inherit' on model 'sale.order': Element '<xpath expr="//button[@name='action_cancel']">' not found in parent view 'sale.view_order_form'
2014-08-08 12:56:55,421 23157 ERROR openerp_test openerp.tools.convert: Parse error in /home/travis/build/OCA/sale-workflow/sale_validity/view/sale_order.xml:5: 
<record id="view_order_form_validity" model="ir.ui.view">
        <field name="name">sale.order.form.validity</field>
        <field name="model">sale.order</field>
        <field name="inherit_id" ref="sale.view_order_form"/>
        <field name="arch" type="xml">
            <data><field name="date_order" position="after">
                <field name="date_validity"/>
            </field>
            <field name="date_order" position="attributes">
                <attribute name="on_change">date_order_change(date_order, date_validity, company_id, context)</attribute>
            </field>
        </data></field>
    </record>
Traceback (most recent call last):
  File "/home/travis/build/OCA/odoo-7.0/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/home/travis/build/OCA/odoo-7.0/openerp/tools/convert.py", line 819, in _tag_record
    id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/travis/build/OCA/odoo-7.0/openerp/addons/base/ir/ir_model.py", line 952, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/home/travis/build/OCA/odoo-7.0/openerp/addons/base/ir/ir_ui_view.py", line 214, in write
    return super(view, self).write(cr, uid, ids, vals, context)
  File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 4298, in write
    self._validate(cr, user, ids, context)
  File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 1572, in _validate
    raise except_orm('ValidateError', '\n'.join(error_msgs))
except_orm: ('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')
2014-08-08 12:56:55,422 23157 ERROR openerp_test openerp: Failed to initialize database `openerp_test`.
Traceback (most recent call last):
  File "/home/travis/build/OCA/odoo-7.0/openerp/cli/server.py", line 97, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname,update_module=update_module)
  File "/home/travis/build/OCA/odoo-7.0/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/home/travis/build/OCA/odoo-7.0/openerp/modules/registry.py", line 203, in get
    update_module)
  File "/home/travis/build/OCA/odoo-7.0/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/home/travis/build/OCA/odoo-7.0/openerp/modules/loading.py", line 350, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/travis/build/OCA/odoo-7.0/openerp/modules/loading.py", line 256, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/travis/build/OCA/odoo-7.0/openerp/modules/loading.py", line 188, in load_module_graph
    load_data(module_name, idref, mode)
  File "/home/travis/build/OCA/odoo-7.0/openerp/modules/loading.py", line 76, in <lambda>
    load_data = lambda *args: _load_data(cr, *args, kind='data')
  File "/home/travis/build/OCA/odoo-7.0/openerp/modules/loading.py", line 124, in _load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode, noupdate, report)
  File "/home/travis/build/OCA/odoo-7.0/openerp/tools/convert.py", line 959, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/travis/build/OCA/odoo-7.0/openerp/tools/convert.py", line 852, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/home/travis/build/OCA/odoo-7.0/openerp/tools/convert.py", line 819, in _tag_record
    id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/travis/build/OCA/odoo-7.0/openerp/addons/base/ir/ir_model.py", line 952, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/home/travis/build/OCA/odoo-7.0/openerp/addons/base/ir/ir_ui_view.py", line 214, in write
    return super(view, self).write(cr, uid, ids, vals, context)
  File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 4298, in write
    self._validate(cr, user, ids, context)
  File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 1572, in _validate
    raise except_orm('ValidateError', '\n'.join(error_msgs))
except_orm: ('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')

```

**Comment by guewen** [comment]
The source of the error lies in the module sale_cancel_reason: https://github.com/OCA/sale-workflow/blob/7.0/sale_cancel_reason/view/sale_view.xml#L9.
However I'm not sure why this error happens and how we could avoid it.

**Comment by yvaucher** [comment]
I relaunched the build so state on branch README.md 7.0 reflects current status of failing on travis

**Comment by yvaucher** [comment]
Fixed in https://github.com/OCA/sale-workflow/pull/21
