### ISSUE TITLE
[14] Sale_order_line_price_history TypeError: Cannot read properties in undefined

### ISSUE THREAD

**Issue by JrVeroy** [OCA/sale-workflow#1772]
Hello I installed the Sale_order_line_price_history module in Odoo 14 enterpise. when click on the icon, and error messeage comes up:
Rastreo de error:
TypeError: Cannot read properties of undefined (reading 'constructor')
    at wrap_context (http://143.198.65.175:8069/web/content/697-2e8d43d/web.assets_backend.js:351:8)
    at http://143.198.65.175:8069/web/content/697-2e8d43d/web.assets_backend.js:355:127
    at reducer (http://143.198.65.175:8069/web/content/137-6661822/web.assets_common.js:113:84)
    at Function.<anonymous> (http://143.198.65.175:8069/web/content/137-6661822/web.assets_common.js:114:97)
    at _.<computed> [as reduce] (http://143.198.65.175:8069/web/content/137-6661822/web.assets_common.js:175:498)
    at eval_contexts (http://143.198.65.175:8069/web/content/697-2e8d43d/web.assets_backend.js:353:136)
    at http://143.198.65.175:8069/web/content/697-2e8d43d/web.assets_backend.js:355:253
    at reducer (http://143.198.65.175:8069/web/content/137-6661822/web.assets_common.js:113:84)
    at Function.<anonymous> (http://143.198.65.175:8069/web/content/137-6661822/web.assets_common.js:114:97)
    at _.<computed> [as reduce] (http://143.198.65.175:8069/web/content/137-6661822/web.assets_common.js:175:498)

I read that this error was an Odoo web client issue, and that the expanded view had to be activated to get rid of the error, how do I do that?

## Module
Sale_order_line_price_history

## Describe the bug
TypeError: Cannot read properties when icon is clicked

## To Reproduce
**Affected versions**:

1. Open new sale order
2. add product
3. click on the price history icon

**Expected behavior**
When click on the icon, price history should be shown.

**Comment by JrVeroy** [comment]
Solved! only needed to clear the browsing cache! Serpents team gave me the pointer! tahnks a lot!
