### ISSUE TITLE
Error when searching sale_rental relational fields

### ISSUE THREAD

**Issue by lasley** [OCA/sale-workflow#178]
Error is displayed when trying to perform Advanced Search on sale_rental in tree view. 

Replication instructions: Advanced Search on sale_rental => `State of the Outgoing Stock Move` `is` `New` => Apply

Error: 

```
2015-07-03 05:57:56,728 23996 ERROR miller_rentals openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 536, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 573, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 306, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 802, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 402, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 884, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 905, in do_search_read
    request.context)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 907, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5129, in search_read
    record_ids = self.search(cr, uid, domain or [], offset=offset, limit=limit, order=order, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 1642, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4638, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4461, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/expression.py", line 646, in __init__
    self.parse(cr, uid, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/expression.py", line 827, in parse
    elif len(path) > 1 and column._type == 'many2one' and column._auto_join:
AttributeError: 'NoneType' object has no attribute '_type'
```

**Comment by lasley** [comment]
I'm stumped. Was this an API change between 7 and 8?
