### ISSUE TITLE
After the module is upgraded to ODOO15, the application is normal.

### ISSUE THREAD

**Issue by digitalliuzg** [OCA/sale-workflow#2157]
issue:
installation  module odoo14 Sale Rental to ODOO15, prompting an installation error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 15.0.20220807\server\odoo\http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 15.0.20220807\server\odoo\http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: Model 'stock.inventory' does not exist in registry.

Demand:
Upgrade module Sale Rental to ODOO15

**Comment by pedrobaeza** [comment]
The module is not migrated, so that's expected. Closing as there's a general issue for tracking the migration of the modules of this repository to v15.
