### ISSUE TITLE
sale_delivery_term is failing its own tests

### ISSUE THREAD

**Issue by bwrsandman** [OCA/sale-workflow#23]
https://travis-ci.org/OCA/sale-workflow/jobs/32663504#L845

```
2014-08-15 19:08:08,998 23135 INFO openerp_test openerp.modules.loading: module sale_delivery_term: loading test/sale_order_demo.yml
2014-08-15 19:08:09,023 23135 TEST openerp_test openerp.tools.yaml_import: In order to test process of the Sale Order, I create sale order
2014-08-15 19:08:09,424 23135 TEST openerp_test openerp.tools.yaml_import: I verify that the onchange was correctly triggered
2014-08-15 19:08:09,426 23135 TEST openerp_test openerp.tools.yaml_import: I create another sale order
2014-08-15 19:08:09,843 23135 TEST openerp_test openerp.tools.yaml_import: I verify that the onchange was correctly triggered
2014-08-15 19:08:09,845 23135 TEST openerp_test openerp.tools.yaml_import: I create the detailed order lines
2014-08-15 19:08:09,850 23135 ERROR openerp_test openerp.tools.yaml_import: (u'Error', u'Delivery term lines are 4. Order line groups are 2. Please create more groups')
Traceback (most recent call last):
File "/home/travis/build/OCA/odoo-7.0/openerp/tools/yaml_import.py", line 867, in process
self._process_node(node)
File "/home/travis/build/OCA/odoo-7.0/openerp/tools/yaml_import.py", line 880, in _process_node
self.process_python(node)
File "/home/travis/build/OCA/odoo-7.0/openerp/tools/yaml_import.py", line 553, in process_python
unsafe_eval(code_obj, {'ref': self.get_id}, code_context)
File "/home/travis/build/OCA/sale-workflow/sale_delivery_term/test/sale_order_demo.yml", line 2, in <module>
In order to test process of the Sale Order, I create sale order
File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 377, in function_proxy
return attr(self._cr, self._uid, [self._id], *args, **kwargs)
File "/home/travis/build/OCA/sale-workflow/sale_delivery_term/sale.py", line 241, in generate_detailed_lines
len(group_ids)))
except_orm: (u'Error', u'Delivery term lines are 4. Order line groups are 2. Please create more groups')
2014-08-15 19:08:09,853 23135 ERROR openerp_test openerp.modules.loading: module sale_delivery_term: an exception occurred in a test
Traceback (most recent call last):
File "/home/travis/build/OCA/odoo-7.0/openerp/modules/loading.py", line 83, in load_test
_load_data(cr, module_name, idref, mode, 'test')
File "/home/travis/build/OCA/odoo-7.0/openerp/modules/loading.py", line 122, in _load_data
tools.convert_yaml_import(cr, module_name, fp, kind, idref, mode, noupdate, report)
File "/home/travis/build/OCA/odoo-7.0/openerp/tools/yaml_import.py", line 931, in yaml_import
yaml_interpreter.process(yaml_string)
File "/home/travis/build/OCA/odoo-7.0/openerp/tools/yaml_import.py", line 867, in process
self._process_node(node)
File "/home/travis/build/OCA/odoo-7.0/openerp/tools/yaml_import.py", line 880, in _process_node
self.process_python(node)
File "/home/travis/build/OCA/odoo-7.0/openerp/tools/yaml_import.py", line 553, in process_python
unsafe_eval(code_obj, {'ref': self.get_id}, code_context)
File "/home/travis/build/OCA/sale-workflow/sale_delivery_term/test/sale_order_demo.yml", line 2, in <module>
In order to test process of the Sale Order, I create sale order
File "/home/travis/build/OCA/odoo-7.0/openerp/osv/orm.py", line 377, in function_proxy
return attr(self._cr, self._uid, [self._id], *args, **kwargs)
File "/home/travis/build/OCA/sale-workflow/sale_delivery_term/sale.py", line 241, in generate_detailed_lines
len(group_ids)))
except_orm: (u'Error', u'Delivery term lines are 4. Order line groups are 2. Please create more groups')
```

**Comment by bwrsandman** [comment]
@eLBati you worked on this, maybe you know the best way to fix these?

Generate 2 groups, maybe?

**Comment by eLBati** [comment]
Hello @bwrsandman this is fixed by https://github.com/OCA/sale-workflow/pull/22
