### ISSUE TITLE
[15] sale_company_currency 

### ISSUE THREAD

**Issue by JackieLuffyDesign** [OCA/sale-workflow#2316]
## Module
Want to install sale_company_currency(for odoo14) in Odoo 15

## Describe the bug
I try to install sale_company_currency (for odoo 14) on the Odoo 15 and get the error below. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /odoo/custom/addons/sale_company_currency/views/sale_order_view.xml:21
Error while validating view:

Element '<field name="amount_total">' cannot be located in parent view

View error context:
{'file': '/odoo/custom/addons/sale_company_currency/views/sale_order_view.xml',
 'line': 2,
 'name': 'sale.order.form',
 'view': ir.ui.view(1538,),
 'view.model': 'sale.order',
 'view.parent': ir.ui.view(806,),
 'xmlid': 'view_order_form'}

## To Reproduce
1. Download sale_company_currency (for odoo 14)
2. Install sale_company_currency in the Odoo 15. 
3. Get the error above. 

**Expected behavior**
Install successful.

**Comment by legalsylvain** [comment]
> Want to install sale_company_currency(for odoo14) in Odoo 15

That is not possible. Please port or finance the port of this module in v15. 
Thanks !
