### ISSUE TITLE
two issues with partner_prospect

### ISSUE THREAD

**Issue by alanljj** [OCA/sale-workflow#238]
module: partner_prospect
version: 8.0
1. when create a new person contact in res.partner, the all person contacts belong to parent company will be updated by user. We sorted partner by updated time.
2. can't create new contact for user of See Own Leads. after uninstalled this module, problem disappeared. I am not sure whether this module issue, here is error log for your reference: 

2015-11-25 01:59:07,767 1738 ERROR mydb openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/addons_geeker/auditlog/models/rule.py", line 215, in create
    new_record = create.origin(self, vals, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/addons_geeker/tko_partner_multiple_phones/res_partner.py", line 43, in create
    res = super(res_partner, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons_geeker/tko_partner_multiple_emails/res_partner.py", line 39, in create
    res = super(res_partner, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/addons/res_partner_strip_name/models.py", line 17, in create
    return super(res_partner_strip_name, self).create(vals)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/res_partner_strip_email/models.py", line 17, in create
    return super(res_partner_strip_email, self).create(vals)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/res/res_partner.py", line 573, in create
    partner = super(res_partner, self).create(vals)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_thread.py", line 381, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4092, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4277, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/opt/odoo/openerp/osv/fields.py", line 1478, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/opt/odoo/addons/mail/mail_thread.py", line 282, in _set_followers
    self.message_subscribe(cr, uid, [id], list(new-old), context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_thread.py", line 1789, in message_subscribe
    }, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/addons/mail/mail_followers.py", line 59, in create
    res = super(mail_followers, self).create(cr, uid, vals, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4092, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 4302, in _create
    recs.recompute()
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/models.py", line 5729, in recompute
    name: rec[name] for name in names
  File "/opt/odoo/openerp/models.py", line 5729, in <dictcomp>
    name: rec[name] for name in names
  File "/opt/odoo/openerp/models.py", line 5613, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/openerp/fields.py", line 812, in **get**
    return record._cache[self]
  File "/opt/odoo/openerp/models.py", line 5996, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/opt/odoo/openerp/fields.py", line 55, in get
    raise self.exception
AccessError: ('AccessError', u'\u7531\u4e8e\u5b89\u5168\u9650\u5236\uff0c\u8bf7\u6c42\u7684\u64cd\u4f5c\u4e0d\u80fd\u88ab\u5b8c\u6210\u3002\u8bf7\u8054\u7cfb\u4f60\u7684\u7cfb\u7edf\u7ba1\u7406\u5458\u3002\n\n(\u5355\u636e\u7c7b\u578b: res.partner, \u64cd\u4f5c: read)')

**Comment by pedrobaeza** [comment]
@oihane can you check this issue?
