### ISSUE TITLE
[8.0] sale_service_project: cannot install on fresh odoo 8 with all dependencies on the server

### ISSUE THREAD

**Issue by Derter** [OCA/sale-workflow#296]
Error:
Traceback (most recent call last):
  File "/home/odoo/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo/odoo/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/home/odoo/odoo/openerp/modules/registry.py", line 197, in setup_models
    model._setup_complete(cr, SUPERUSER_ID)
  File "/home/odoo/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoo/odoo/openerp/models.py", line 3028, in _setup_complete
    field.setup_triggers(self.env)
  File "/home/odoo/odoo/openerp/fields.py", line 610, in setup_triggers
    self._setup_dependency([], model, path.split('.'))
  File "/home/odoo/odoo/openerp/fields.py", line 643, in _setup_dependency
    self._setup_dependency(path0 + [head], comodel, tail)
  File "/home/odoo/odoo/openerp/fields.py", line 643, in _setup_dependency
    self._setup_dependency(path0 + [head], comodel, tail)
  File "/home/odoo/odoo/openerp/fields.py", line 624, in _setup_dependency
    fields = [model._fields[head]]
KeyError: 'hours'

Thanks for any help

**Comment by paulius-sladkevicius** [comment]
Looks that this module won't work together with timesheet_task module, please check if it's your case.

**Comment by pedrobaeza** [comment]
Answered, so I close.
