### ISSUE TITLE
[sale_quotation_number][8.0][BUG] Error when duplicate sale quotation/sale order

### ISSUE THREAD

**Issue by andhit-r** [OCA/sale-workflow#303]
module: sale_quotation_number
version: 8.0

**Steps to reproduce**
1. Open any existing sales quotation/order
2. Duplicate

**Current behavior**

Exception raised:
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/http.py", line 540, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/http.py", line 577, in dispatch
    result = self._call_function(*_self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/http.py", line 313, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/http.py", line 310, in checked_call
    return self.endpoint(_a, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/http.py", line 806, in __call__
    return self.method(_args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/http.py", line 406, in response_wrap
    response = f(_args, *_kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/api.py", line 439, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/api.py", line 443, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/addons/sale_quotation_number/model/sale_order.py", line 33, in copy
    return super(SaleOrder, self).copy(default=default)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3147807-8-0-fbff14/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
TypeError: copy() got an unexpected keyword argument 'default'

**Expected behavior**

No exception raised

**Comment by StefanRijnhart** [comment]
@andhit-r came across this bug only today. I believe it to be fixed with #473. On that PR's runbot, it is possible again to copy sale orders again.
