### ISSUE TITLE
can't install sale_rental

### ISSUE THREAD

**Issue by petern1** [OCA/sale-workflow#318]
Hello!

I just tried to install sale_rental on my odoo 8 server, but I am getting this error while installing:

```
 Traceback (most recent call last):
  File "/home/openerp/odoo-8.0-20151105/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/openerp/odoo-8.0-20151105/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/openerp/odoo-8.0-20151105/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/openerp/odoo-8.0-20151105/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/openerp/odoo-8.0-20151105/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/openerp/odoo-8.0-20151105/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/openerp/odoo-8.0-20151105/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/openerp/odoo-8.0-20151105/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/openerp/odoo-8.0-20151105/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/openerp/odoo-8.0-20151105/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openerp/odoo-8.0-20151105/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/openerp/odoo-8.0-20151105/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openerp/odoo-8.0-20151105/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/openerp/odoo-8.0-20151105/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/openerp/odoo-8.0-20151105/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/openerp/odoo-8.0-20151105/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/openerp/odoo-8.0-20151105/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/openerp/odoo-8.0-20151105/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/openerp/odoo-8.0-20151105/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/openerp/odoo-8.0-20151105/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/openerp/odoo-8.0-20151105/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/openerp/odoo-8.0-20151105/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/openerp/odoo-8.0-20151105/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openerp/custom_addons/bt_helper/ir_model_data_ext.py", line 39, in _update
    return super(ir_model_data_ext, self)._update(cr, uid, model, module, values, xml_id, store, noupdate, mode, res_id, context)
  File "/home/openerp/odoo-8.0-20151105/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openerp/odoo-8.0-20151105/openerp/addons/base/ir/ir_model.py", line 1025, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/home/openerp/odoo-8.0-20151105/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openerp/odoo-8.0-20151105/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/openerp/custom_addons_eigene/sale_rental/rental.py", line 594, in write
    self._get_rental_push_pull_rules().iteritems():
  File "/home/openerp/odoo-8.0-20151105/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/openerp/custom_addons_eigene/sale_rental/rental.py", line 573, in _get_rental_push_pull_rules
    self.out_type_id.default_location_dest_id, self.env.context),
  File "/home/openerp/odoo-8.0-20151105/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openerp/odoo-8.0-20151105/openerp/addons/stock/stock.py", line 3536, in _format_rulename
    return obj.code + ': ' + from_loc.name + ' -> ' + dest_loc.name
ParseError: "coercing to Unicode: need string or buffer, bool found" while parsing /home/openerp/custom_addons_eigene/sale_rental/rental_data.xml:49, near
<record id="stock.warehouse0" model="stock.warehouse">
    <field name="rental_allowed">1</field> <!-- I know it is the default value, but I set it here to go through the write() and create the pull rules -->
    <field name="rental_route_id" ref="route_warehouse0_rental"/>
    <field name="sell_rented_product_route_id" ref="route_warehouse0_sell_rented_product"/>
</record>
OK

```

Any ideas how to fix this?
Thank you

**Comment by pedrobaeza** [comment]
Use last version.
