### ISSUE TITLE
[10.0] sale_automatic_workflow - shipping policy setting 

### ISSUE THREAD

**Issue by seancallahan88** [OCA/sale-workflow#511]
If a workflow is set on a sale with shipping setting "Ship products when some are available, and allow back orders" (setting applied in either Sales-Settings or Workflow Automation Configuration) and "Confirm and Transfer Picking" then the "Confirm and Transfer Picking" does  not perform as expected.

Expected behavior: One validated picking for available products, One backorder created and in waiting availability state.
Current behavior: One picking at waiting availability state.

Example:
Customer orders 1x ice cream (not in stock) and 1x laptop (in stock).
If we are allowing products to be shipped seperatly and workflow is automatically validating pickings, then in theory laptop should be shipped (validated picking) and ice cream put on back order. Current behavior is that workflow does not touch picking, even with Confirm and Transfer Picking.

Tested on Odoo10E with demonstration data.

**Comment by seancallahan88** [comment]
Just wanted to add that if you change the default picking domain to include 'partially_available' you get this error:

2017-07-23 03:09:09,973 3915 ERROR test odoo.addons.sale_automatic_workflow.models.automatic_workflow_job: Error during an automatic workflow action.
Traceback (most recent call last):
  File "/var/lib/odoo/custom_addons/sale_automatic_workflow/models/automatic_workflow_job.py", line 23, in savepoint
    yield
  File "/var/lib/odoo/custom_addons/sale_automatic_workflow/models/automatic_workflow_job.py", line 70, in _validate_pickings
    pickings.validate_picking()
  File "/var/lib/odoo/custom_addons/sale_automatic_workflow/models/stock_picking.py", line 21, in validate_picking
    self.do_transfer()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/delivery/models/stock_picking.py", line 113, in do_transfer
    self.ensure_one()
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4825, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: stock.picking(51, 52)

**Comment by dvdhinesh** [comment]
@seancallahan88 
I hope this bug was related to this PR #531 
Once it was merged in V9, i will make a PR to V10.
Meanwhile test the patch and make a review.

**Comment by seancallahan88** [comment]
I ended up making my own changes which is exactly what you have :

 for picking in pickings:
            with savepoint(self.env.cr):
                picking.validate_picking()

and it works fine 

except commit vs savepoint...unsure about this because savepoint is used in all the v10 workflow functions....I am unclear on the reason why this was changed?

**Comment by dvdhinesh** [comment]
@seancallahan88 Take a look at this commit: f58b31aea46695d1f7112e1dc9076c627c3e73f5
It was `commit` till V9 and upgraded to `savepoint` from V10
