### ISSUE TITLE
Italian translation bug in Calendar menu (odoo 9.0)

### ISSUE THREAD

**Issue by Mitconsulting** [OCA/sale-workflow#578]
I found a bug in the Italian translation. Every time I edit an appointment in the calendar I get the following error. In English it works without problems.

Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\http.py", line 643, in _handle_exception
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\http.py", line 680, in dispatch
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\http.py", line 316, in _call_function
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\http.py", line 309, in checked_call
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\http.py", line 959, in __call__
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\http.py", line 509, in response_wrap
  File "C:\Program Files\Odoo 9.0-20160115\server\openerp\addons\web\controllers\main.py", line 892, in call_kw
  File "C:\Program Files\Odoo 9.0-20160115\server\openerp\addons\web\controllers\main.py", line 884, in _call_kw
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\api.py", line 354, in old_api
  File "C:\Program Files\Odoo 9.0-20160115\server\openerp\addons\mail\models\mail_thread.py", line 362, in fields_view_get
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\api.py", line 490, in new_api
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\models.py", line 1536, in fields_view_get
  File "C:\Program Files\Odoo 9.0-20160115\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files\Odoo 9.0-20160115\server\openerp\addons\base\ir\ir_ui_view.py", line 640, in read_combined
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68106)
  File "parser.pxi", line 1785, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102455)
  File "parser.pxi", line 1673, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101284)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96466)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91757)
XMLSyntaxError: Opening and ending tag mismatch: br line 21 and p, line 23, column 37

**Comment by eLBati** [comment]
@Mitconsulting which module do you think it's involved?

**Comment by Mitconsulting** [comment]
I solved. I have updated the version of odoo.9
