### ISSUE TITLE
[Odoo 10.0] Incompatibility between sale_order_margin_percent and sale_order_revision

### ISSUE THREAD

**Issue by vinclar** [OCA/sale-workflow#599]
Odoo 10.0 CE
Affected modules: sale_order_margin_percent and sale_order_revision
When you try to create a sale order revision with margin percent installed, it throws this error.
After uninstall sale_order_margin_percent it disappears 
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/models.py", line 3018, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "/odoo/odoo-server/odoo/models.py", line 5208, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/odoo/odoo-server/odoo/fields.py", line 910, in __get__
    self.determine_value(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1022, in determine_value
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 976, in compute_value
    self._compute_value(records)
  File "/odoo/odoo-server/odoo/fields.py", line 967, in _compute_value
    getattr(records, self.compute)()
  File "/odoo/custom/addons/sale_order_margin_percent/models/sale_order_margin.py", line 15, in _compute_percent
    if self.margin and self.amount_untaxed:
  File "/odoo/odoo-server/odoo/fields.py", line 904, in __get__
    record.ensure_one()
  File "/odoo/odoo-server/odoo/models.py", line 4820, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: sale.order(80, 78)

**Comment by rousseldenis** [comment]
@vinclar No, the error is located only in sale_order_margin_percent.

@rafaelbn The compute method is multi by default.

**Comment by vinclar** [comment]
Do I need to change the title to make it mor visible to the developers?
There is also an incompatibility between sale_isolated_quotation and sale_order_revision

**Comment by vinclar** [comment]
Seems solved
Tested right now, and works flawlessly

**Comment by rafaelbn** [comment]
AS @vinclar said solved then closing
